extends Node3D
## Greenhollow Clearing — level one.
##
## The scene file next to this script is generated by tools/build_clearing.gd, but
## it is a normal editable scene: open it and move things around. If you re-run
## the generator it will overwrite your edits, so past a certain point stop
## running it and edit here by hand.


func _ready() -> void:
	# Nature-kit models import with standard PBR shading; match the flat toon
	# look the rest of the world uses.
	Toonify.apply(self)
